spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pet-buddy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      hibernate:
        order_by.default_null_ordering: last
    show-sql: false
  profiles:
    active: dev

  # import data for database
  config:
    import:
      - classpath:animal-data.yml
      - classpath:animal-attribute-data.yml
      - classpath:amenity-data.yml
      - classpath:animal-amenity-data.yml

keycloak:
  resource-roles-claim: "pet-buddy-client"
  claim-name: "preferred_username"

logging:
  level:
    root: info

server:
  port: 8081

sentry:
  dsn: https://aea7d4722318a9965e1ef62e26a4109b@o4507593891184640.ingest.de.sentry.io/4507593901998160

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"

header-name:
  timezone: "Accept-Timezone"
  role: "Accept-Role"

url:
  chat:
    subscription-pattern: "/topic/messages/%d/%s"
