spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pet-buddy
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      hibernate:
        order_by.default_null_ordering: last
    show-sql: false
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 150MB

  # import data for database
  config:
    import:
      - classpath:animal-data.yml
      - classpath:animal-attribute-data.yml
      - classpath:amenity-data.yml
      - classpath:animal-amenity-data.yml

keycloak:
  resource-roles-claim: "pet-buddy-client"
  claim-name: "preferred_username"

logging:
  level:
    root: INFO

server:
  port: 8081

sentry:
  dsn: https://aea7d4722318a9965e1ef62e26a4109b@o4507593891184640.ingest.de.sentry.io/4507593901998160

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"

header-name:
  timezone: "Accept-Timezone"
  role: "Accept-Role"

url:
  chat:
    topic:
      base: "/topic/messages"
      pattern: "/topic/messages/%d/%s"
  session:
    topic:
      base: "/topic/session"
      pattern: "/topic/session/%s"

firebase:
  key:
    path: secret/petbuddy-firebase-private-key.json
  project:
    id: petbuddy-d6479
  bucket:
    link: petbuddy-d6479.appspot.com
  photo:
    directory: ${FIREBASE_PHOTO_DIRECTORY}
    expiration:
      max-seconds: 6        # 6 hours
      threshold-seconds: 1   # 0.5 hour
