spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pet-buddy
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect

keycloak:
  resource-roles-claim: "pet-buddy-client"
  claim-name: "preferred_username"

logging:
  level:
    root: info

server:
  port: 8081