spring:
  application.name: petBuddy-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/pet-buddy
  keycloak:
    resource-roles-claim: "pet-buddy-client"
    claim-name: "preferred_username"

logging:
  level:
    root: info
